name: CI

on:
  pull_request:
    branches:
      - stage
      - dev
      - hotfix
      - 'feature/**'
      - 'fix/**'
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      build_artifact: ${{ steps.upload_build.outputs.artifact }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Nuxt
        run: pnpm run dev:prepare

      - name: Build
        run: pnpm run build

      - name: Upload build artifacts
        id: upload_build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: .

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Publish Changeset
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-changes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}