name: Release

on:
  pull_request:
    branches:
      - stage
      - dev
      - feature/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/build.yml  # <-- use the existing build.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build   # <-- depends on the build job
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Nuxt
        run: pnpm run dev:prepare

      - name: Publish Changeset
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-changes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
