name: Release

on:
  pull_request:
    branches:
      - stage
      - dev
      - feature/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build workflow
        uses: ./.github/workflows/build.yml

      - name: Publish Changeset
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-changes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
